/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignInScreen` | `/SignInScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignUpScreen` | `/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/WelcomeScreen` | `/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AboutScreen` | `/AboutScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CommunityScreen` | `/CommunityScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MealPlanScreen` | `/MealPlanScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/SignInScreen` | `/SignInScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/SignUpScreen` | `/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/WelcomeScreen` | `/WelcomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AboutScreen` | `/AboutScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/CommunityScreen` | `/CommunityScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MealPlanScreen` | `/MealPlanScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/SignInScreen${`?${string}` | `#${string}` | ''}` | `/SignInScreen${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/SignUpScreen${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/WelcomeScreen${`?${string}` | `#${string}` | ''}` | `/WelcomeScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AboutScreen${`?${string}` | `#${string}` | ''}` | `/AboutScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/CommunityScreen${`?${string}` | `#${string}` | ''}` | `/CommunityScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MealPlanScreen${`?${string}` | `#${string}` | ''}` | `/MealPlanScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignInScreen` | `/SignInScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignUpScreen` | `/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/WelcomeScreen` | `/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AboutScreen` | `/AboutScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CommunityScreen` | `/CommunityScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MealPlanScreen` | `/MealPlanScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
